repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.64.1
    hooks:
      - id: cfn-python-lint
        name: lint aws cloudformation templates
        exclude: '\.pre-commit-config.yaml'

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.49.0
    hooks:
      - id: golangci-lint
